### ISSUE TITLE
error: Bad file: /tmp/tito/rpmbuild-subscription-manageruzmptpdv/SOURCES/subscription-manager-cockpit-1.28.29.tar.gz: No such file or directory

### ISSUE THREAD

**Issue by Sergiodcm00** [Djelibeybi/build-subscription-manager#1]
I check on OEL8, RH8 and CentOS8 with no lucky

```
Creating output directory: /tmp/tito
Building package [subscription-manager-1.28.29-3]
Wrote: /tmp/tito/subscription-manager-1.28.29.tar.gz
error: Bad file: /tmp/tito/rpmbuild-subscription-manageruzmptpdv/SOURCES/subscription-manager-cockpit-1.28.29.tar.gz: No such file or directory

ERROR: Error running command: rpmbuild --eval '%undefine scl' --define "_topdir /tmp/tito/rpmbuild-subscription-manageruzmptpdv" --define "_sourcedir /tmp/tito/rpmbuild-subscription-manageruzmptpdv/SOURCES" --define "_builddir /tmp/tito/rpmbuild-subscription-manageruzmptpdv/BUILD" --define "_srcrpmdir /tmp/tito" --define "_rpmdir /tmp/tito" --define 'dist .el8' --nodeps -bs /tmp/tito/rpmbuild-subscription-manageruzmptpdv/SOURCES/subscription-manager-1.28.29/subscription-manager.spec
Status code: 1

Command output: ['error: Bad file: /tmp/tito/rpmbuild-subscription-manageruzmptpdv/SOURCES/subscription-manager-cockpit-1.28.29.tar.gz: No such file or directory', '']

Traceback (most recent call last):
File "/usr/bin/tito", line 11, in <module>
load_entry_point('tito==0.6.21', 'console_scripts', 'tito')()
File "/usr/lib/python3.6/site-packages/tito/cli.py", line 910, in main
CLI().main(sys.argv[1:])
File "/usr/lib/python3.6/site-packages/tito/cli.py", line 209, in main
return module.main(argv)
File "/usr/lib/python3.6/site-packages/tito/cli.py", line 392, in main
return builder.run(self.options)
File "/usr/lib/python3.6/site-packages/tito/builder/main.py", line 162, in run
self.srpm()
File "/usr/lib/python3.6/site-packages/tito/builder/main.py", line 246, in srpm
output = run_command_func(cmd)
File "/usr/lib/python3.6/site-packages/tito/common.py", line 353, in run_command_print
raise RunCommandException(command, status, "\n".join(output))
tito.exception.RunCommandException: Error running command: rpmbuild --eval '%undefine scl' --define "_topdir /tmp/tito/rpmbuild-subscription-manageruzmptpdv" --define "_sourcedir /tmp/tito/rpmbuild-subscription-manageruzmptpdv/SOURCES" --define "_builddir /tmp/tito/rpmbuild-subscription-manageruzmptpdv/BUILD" --define "_srcrpmdir /tmp/tito" --define "_rpmdir /tmp/tito" --define 'dist .el8' --nodeps -bs /tmp/tito/rpmbuild-subscription-manageruzmptpdv/SOURCES/subscription-manager-1.28.29/subscription-manager.spec

cp: cannot stat '/tmp/tito/subscription-manager-1.28.29-3.el8.src.rpm': No such file or directory

Not signing the packages. One or more of the key.asc and passphrase files and the GPG_NAME_EMAIL environment variable are missing.
```

**Comment by Djelibeybi** [comment]
I'll have to take a look as it's been a while since I wrote/used this, to be honest.

**Comment by bamorrow** [comment]
I get the same error

**Comment by Djelibeybi** [comment]
Sorry it took so long to fix, it kind of dropped off my radar. :(
